spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost:8092
                    zk-nodes: localhost
            bindings:
                input:
                    binder: kafka
                    destination: topic
                output:
                    binder: kafka
                    destination: topic
format: DD/MM/YYY hh:mm:ss
fixed-delay: 3000
