version: '2'
services:
    nifi:
        image: apache/nifi:latest
        ports:
        - "8090:8080"
        volumes:
        - C:/dev/share/nifi/templates/:/opt/nifi/nifi-current/conf/templates/
        networks:
        - pipeline
networks:
    pipeline:
        external: true
