version: '2'
services:
    nifi:
        image: apache/nifi:latest
        ports:
        - "8090:8080"
        volumes:
        - ./templates/:/opt/nifi/nifi-current/conf/templates/
        networks:
        - insight
networks:
    insight:
        external: true
